version: '3'
services:
  db:
    image: mariadb
    restart: always
    container_name: calendy-mariadb
    volumes:
      - calendy-data:/var/lib/mariadb/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: calendy
    ports: 
    - 3309:3306

volumes:
  calendy-data:
