version: '3'
services:
  db:
    image: mariadb
    restart: always
    container_name: calendy-mariadb-dev
    volumes:
      - calendy-data:/var/lib/mariadb/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: calendy
      MYSQL_TCP_PORT: 3309
      MYSQL_UNIX_PORT: 3309
    ports: 
      - 3309:3309

volumes:
  calendy-data: